### ISSUE TITLE
Skipping acquire of configured file 'main/binary-i386/Packages'

### ISSUE THREAD

**Issue by vejc94** [dkogan/mrcal#2]
when running `apt-get update` the terminal throws the message:
`
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'http://mrcal.secretsauce.net/packages/focal/public focal InRelease' doesn't support architecture 'i386'
`
I have installed the library in an Ubuntu 20.04. version.

**Comment by dkogan** [comment]
Hi. The provided packages are built for the amd64 architecture. I'm not providing i386 packages, since 32-bit-only x86 machines haven't been manufactured for almost 20 years now. Unless there's a compelling reason to stick with i386, you should use the amd64 builds of your OS.

For mrcal, specifically, on i386 you should build from source. I haven't tried it on i386 boxes, but there's no reason it shouldn't work.
